name: 'perk_analytics'
version: '1.0.0'
config-version: 2

profile: 'perk_analytics'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

# Load raw CSVs into DuckDB before running models
on-run-start:
  - "{{ load_raw_csvs() }}"

models:
  perk_analytics:
    staging:
      +materialized: view
      +schema: staging

    intermediate:
      +materialized: view
      +schema: intermediate

    marts:
      +materialized: table
      +schema: marts
